### ISSUE TITLE
 rx.exceptions.OnErrorNotImplementedException

### ISSUE THREAD

**Issue by rajashripawar11** [NaikSoftware/StompProtocolAndroid#117]
Getting below exception while onNext()

 E/WebSocketsConnectionProvider: onError
                                                                 rx.exceptions.OnErrorNotImplementedException
                                                                     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                     at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                     at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                     at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onError(OnSubscribeFilter.java:90)
                                                                     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
                                                                     at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
                                                                     at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182)
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335)
                                                                     at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
                                                                     at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
                                                                     at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
                                                                     at ua.naiksoftware.stomp.AbstractConnectionProvider.emitMessage(AbstractConnectionProvider.java:138)
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:83)
                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:342)
                                                                     at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:595)
                                                                     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:361)
                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:206)
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:277)
                                                                     at java.lang.Thread.run(Thread.java:762)
                                                                  Caused by: java.util.NoSuchElementException
                                                                     at java.util.Scanner.skip(Scanner.java:1747)
                                                                     at java.util.Scanner.skip(Scanner.java:1764)
                                                                     at ua.naiksoftware.stomp.client.StompMessage.from(StompMessage.java:91)
                                                                     at ua.naiksoftware.stomp.client.StompClient$$Lambda$1.call(Unknown Source)
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                                                                     at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91) 
                                                                     at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94) 
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182) 
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335) 
                                                                     at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) 
                                                                     at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) 
                                                                     at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) 
                                                                     at ua.naiksoftware.stomp.AbstractConnectionProvider.emitMessage(AbstractConnectionProvider.java:138) 
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:83) 
                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:342) 
                                                                     at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:595) 
                                                                     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:361) 
                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:206) 
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:277) 
                                                                     at java.lang.Thread.run(Thread.java:762) 
                                                                  Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: GenericMessage [payload=byte[33], headers={simpMessageType=OTHER, stompCommand=RECEIPT, simpSessionId=58}]
                                                                     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
                                                                     at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91) 
                                                                     at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94) 
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerNext(OnSubscribeConcatMap.java:182) 
                                                                     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onNext(OnSubscribeConcatMap.java:335) 
                                                                     at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304) 
                                                                     at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219) 
                                                                     at rx.subjects.PublishSubject.onNext(PublishSubject.java:72) 
                                                                     at ua.naiksoftware.stomp.AbstractConnectionProvider.emitMessage(AbstractConnectionProvider.java:138) 
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:83) 
                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:342) 
                                                                     at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:595) 
                                                                     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:361) 
                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:206) 
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:277) 
                                                                     at java.lang.Thread.run(Thread.java:762)

**Comment by forresthopkinsa** [comment]
Follow the instructions and put an `onError` handler in your code.

If it _is_ there, or if you're confused, **paste your code** so that someone can appropriately help you.

Don't publish bug reports without code.
