### ISSUE TITLE
java.lang.Exception: java.net.ProtocolException: Expected HTTP 101 response but was '200 '

### ISSUE THREAD

**Issue by 171505116** [NaikSoftware/StompProtocolAndroid#138]
Error
java.lang.Exception: java.net.ProtocolException: Expected HTTP 101 response but was '200 '
    at ua.naiksoftware.stomp.OkHttpConnectionProvider$1.onFailure(OkHttpConnectionProvider.java:84)
    at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:784)
 Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '200 '
    at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
    at java.lang.Thread.run(Thread.java:784)

**Comment by 171505116** [comment]
url "ws://127.0.0.1:8080/density/"
chang
"ws://172.18.171.167:8080/density/websocket"

add "/websocket"

**Comment by NaikSoftware** [comment]
Yes, it looks like you need add /websocket prefix to your URL.

**Comment by seefutureLee** [comment]
i met the same bug

**Comment by ndorigatti** [comment]
Hello, sorry for reupping an old post, but I do have the same issue, and can't face it.
I'm using example-client and changed to my sockJS provided websocket:
wss://ourcompanydomain.it/gateway/websocket

I tried using OkHttp, the connections switches to https (accept the token i've put in the headers) but then gives 200 instead of 101.

If I use JWS instead i got a 503 error.

Using javascript library for stomp we get no issues and connection upgrade 101.

My url ends with /websocket but I do not understand whats wrong. Server is exposing websocket via spring boot application same as the example server...

**Comment by ndorigatti** [comment]
I found the issue! My url ends with /gateway/websocket but i did not understand that you have to add another /websocket!
Using /gateway/websocket/websocket solves the issue!!!
