### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by dimonik** [NaikSoftware/StompProtocolAndroid#16]
I'm using StompProtocolAndroid:1.1.2
my build.gradle for App is http://pastebin.com/pJ7v2wQC

This is what i get immediately after run of sample app 1-to-1 as your readme example:

FATAL EXCEPTION:  main
                  Process: com.example.naikstomp, PID: 21778
                  java.lang.NoSuchMethodError: No virtual method ua_naiksoftware_stomp_WebSocketsConnectionProvider$$Lambda$6_lambda$getLifecycleReceiver$3(Lrx/Subscriber;)V in class Lua/naiksoftware/stomp/WebSocketsConnectionProvider; or its super classes (declaration of 'ua.naiksoftware.stomp.WebSocketsConnectionProvider' appears in /data/app/com.example.naikstomp-1/base.apk)
                      at ua.naiksoftware.stomp.WebSocketsConnectionProvider$$Lambda$6.call(Unknown Source)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                      at rx.Observable.subscribe(Observable.java:10247)
                      at rx.Observable.subscribe(Observable.java:10214)
                      at rx.Observable.subscribe(Observable.java:10019)
                      at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:74)
                      at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:62)
                      at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:49)
                      at com.example.naikstomp.MainActivity.stomp_test(MainActivity.java:36)
                      at com.example.naikstomp.MainActivity.onResume(MainActivity.java:30)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
                      at android.app.Activity.performResume(Activity.java:6768)

**Comment by dimonik** [comment]
I will answer by myself:

This error caused by compilation of the project with Jack compiler.
To avoid use default + retrolambda library.

**Comment by wlals822** [comment]
@dimonik  Hi I met the same problem.
You mean you used retrolamda library?

**Comment by dimonik** [comment]
I don't remember exactly what i used, my last working configuration is
https://pastebin.com/z6zEnD47

**Comment by ntrp** [comment]
The problem is arising again if using the latest version of Android Studio with the new desugar bytecode processor..

**Comment by forresthopkinsa** [comment]
I can confirm, I'm experiencing this problem right now as well.

**Comment by forresthopkinsa** [comment]
I'm using the new Android Studio Canary 7 with **native Java 8 compilation**. Jack is out of the toolchain and I'm still having this problem. I just wasted almost an entire day making my project not depend on Jack and I'm still having the problem nonetheless lol

**Comment by LuisBonsembiante** [comment]
Hi @dimonik thanks for you collaboration Im working with the last version of android studio and java 8 compilation, I have this problem... you working in any solution, thanks
