### ISSUE TITLE
Network communication error in android P

### ISSUE THREAD

**Issue by BhadreshChavada** [NaikSoftware/StompProtocolAndroid#165]
I am passing https server url in socket connection still getting error java.net.UnknownServiceException: CLEARTEXT communication to *URL* not permitted by network security policy. 
at ua.naiksoftware.stomp.provider.OkHttpConnectionProvider$1.onFailure(OkHttpConnectionProvider.java:84)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
        at okhttp3.internal.ws.RealWebSocket$2.onFailure(RealWebSocket.java:221)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

Except the android P working fine.

**Comment by Mukesh1507** [comment]
@BhadreshChavada  use  android:usesCleartextTraffic="true" in manifiest or declare a network security config (networkSecurityConfig).
Network config -https://developer.android.com/training/articles/security-config
