### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method 

### ISSUE THREAD

**Issue by LuisBonsembiante** [NaikSoftware/StompProtocolAndroid#52]
Hu I have this problem with the last android studio java 1.8..... the lib doesnt work when set the topic or try to connect...help I need this for urgent project.

FATAL EXCEPTION: main
Process: com.example.naikstomp, PID: 21778
java.lang.NoSuchMethodError: No virtual method ua_naiksoftware_stomp_WebSocketsConnectionProvider$$Lambda$6_lambda$getLifecycleReceiver$3(Lrx/Subscriber;)V in class Lua/naiksoftware/stomp/WebSocketsConnectionProvider; or its super classes (declaration of 'ua.naiksoftware.stomp.WebSocketsConnectionProvider' appears in /data/app/com.example.naikstomp-1/base.apk)
at ua.naiksoftware.stomp.WebSocketsConnectionProvider$$Lambda$6.call(Unknown Source)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
at rx.Observable.subscribe(Observable.java:10247)
at rx.Observable.subscribe(Observable.java:10214)
at rx.Observable.subscribe(Observable.java:10019)
at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:74)
at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:62)
at ua.naiksoftware.stomp.client.StompClient.connect(StompClient.java:49)
at com.example.naikstomp.MainActivity.stomp_test(MainActivity.java:36)
at com.example.naikstomp.MainActivity.onResume(MainActivity.java:30)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
at android.app.Activity.performResume(Activity.java:6768)

**Comment by forresthopkinsa** [comment]
Are you using Android Studio Canary 8 or Canary 9?

Try replacing your Gradle compile line with the following (use alpha8.1 if you're on Canary 8):

`compile 'com.github.forresthopkinsa:StompProtocolAndroid:1.3.2-alpha9.1'`

And let me know if it works for you or not.

**Comment by NaikSoftware** [comment]
Please advertise you fork in you account :)

**Comment by NaikSoftware** [comment]
@LuisBonsembiante you are use desugar or retrolambda?

**Comment by forresthopkinsa** [comment]
@NaikSoftware I'm not advertising, I'm letting people know that there's a working version. This is Github, I'm not gaining anything from them using it. What do I gain from them using my fork?

You said it yourself, you don't have a lot of time for open-source projects right now. That's totally fine, I don't blame you, but there's no reason to not let them use my (functional) fork of it, at least until it's stable enough to merge upstream.

**Comment by violetbax** [comment]
I use retrolambda and have the same problem

**Comment by forresthopkinsa** [comment]
@violetbax What versions of Java and Android-Gradle plugin are you using?

**Comment by LuisBonsembiante** [comment]
Guys I have the solution, you must not use java 1.8 because is deprecated in android and java is discontinued like a language, you should be use in the next implementation Codelin. We solved the problem change the lambda implementaton to anonymal class implementation, and then you need use http://url/websocket/websocket if you use http or http and use ws://url/websocket/ if you use ws.

**Comment by forresthopkinsa** [comment]
@LuisBonsembiante No, Java 1.8 is supported, and Java is definitely not discontinued. If Kotlin is working for you then that's great, but Kotlin is **not** the solution to this problem.

**Comment by violetbax** [comment]
@forresthopkinsa, I use Java 1.8 and 2.3.3 version of Gradle

**Comment by forresthopkinsa** [comment]
@violetbax Okay. Are you using Retrolambda or Jack? (or both?)

**Comment by violetbax** [comment]
I've wrote it before, I use retrolambda

**Comment by forresthopkinsa** [comment]
@violetbax Oh shoot, you're right, sorry about that. I wasn't paying attention haha

At the risk of Naik deleting my comment (lol) I'm gonna ask you to replace your Gradle dependency for this project with the following:

    compile 'com.github.forresthopkinsa:StompProtocolAndroid:1.3.2-alpha9.1'

Just as a TEST to see if it fixes your problem.

**Comment by forresthopkinsa** [comment]
@violetbax Any updates?
