### ISSUE TITLE
NPE on rotate/restart

### ISSUE THREAD

**Issue by steviemo** [NaikSoftware/StompProtocolAndroid#61]
Hi @NaikSoftware 
Sometimes on restart and sometimes on rotate of the device I get the following error:

```
08-21 20:06:33.203 25646-25730/co.oroson.android D/WebSocketsConnectionProvider: onWebsocketHandshakeReceivedAsClient with response: 101 
08-21 20:06:33.205 25646-25730/co.oroson.android D/WebSocketsConnectionProvider: onOpen with handshakeData: 101 
08-21 20:06:33.206 25646-25730/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: OPENED
08-21 20:06:33.207 25646-25730/co.oroson.android E/WebSocketsConnectionProvider: onError
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void rx.Subscriber.onNext(java.lang.Object)' on a null object reference
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:151)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:29)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onOpen(WebSocketsConnectionProvider.java:97)
                                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketOpen(WebSocketClient.java:311)
                                                                                     at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:720)
                                                                                     at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:301)
                                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:173)
                                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
                                                                                     at java.lang.Thread.run(Thread.java:761)
08-21 20:06:33.207 25646-25730/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: ERROR
08-21 20:06:33.207 25646-25730/co.oroson.android E/WebSocketsConnectionProvider: onError
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void rx.Subscriber.onNext(java.lang.Object)' on a null object reference
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:151)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:29)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:116)
                                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:339)
                                                                                     at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:722)
                                                                                     at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:301)
                                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:173)
                                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
                                                                                     at java.lang.Thread.run(Thread.java:761)
08-21 20:06:33.207 25646-25730/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: ERROR
08-21 20:06:33.208 25646-25730/co.oroson.android E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                                                                   Process: co.oroson.android, PID: 25646
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void rx.Subscriber.onNext(java.lang.Object)' on a null object reference
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:151)
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:29)
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:116)
                                                                       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:236)
                                                                       at java.lang.Thread.run(Thread.java:761)
```

I configured the stomp client as per your example project - does this error ring any bells for you?

Thanks,
Stephen

**Comment by forresthopkinsa** [comment]
Can you really easily reproduce it? Can you do some testing for me?

**Comment by steviemo** [comment]
Yeah I can recreate it on a device after about 4 or 5 rotations. So I have the stomp client wrapped in a bound service so it can be shared across multiple activities. If I remove the stompClient.lifecycle() logic then it seems to work fine however this isn't useful at all. Here is my code for the service:

```
public class WebSocketService extends Service {
	private final IBinder binder = new WebSocketBinder();
    private StompClient stompClient;
    
    public final class WebSocketBinder extends Binder {
        public WebSocketService getService() {
            return WebSocketService.this;
        }
    }
    
    @Nullable
    @Override
    public IBinder onBind(final Intent intent) {
        Log.i(TAG, "onBind");
        connect();
        return binder;
    }

    @Override
    public boolean onUnbind(final Intent intent) {
        Log.i(TAG, "onUnbind");
        disconnect();
        return false;
    }
    
    private void connect() {
        Log.i(TAG, "Attempting to connect to websocket");
        if (null != stompClient) {
            Log.i(TAG, "Stomp client already created");
            return;
        }

        stompClient = Stomp.over(WebSocket.class, Config.WS_SERVICE_URL);

        lifecycleSubscription = stompClient.lifecycle()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Action1<LifecycleEvent>() {
                    @Override
                    public void call(final LifecycleEvent lifecycleEvent) {
                        switch (lifecycleEvent.getType()) {
                            case OPENED:
                                Log.i(TAG, "WS connection opened");
                                break;
                            case ERROR:
                                Log.e(TAG, "WS connection error.", lifecycleEvent.getException());
                                break;
                            case CLOSED:
                                Log.i(TAG, "WS connection closed.", lifecycleEvent.getException());
                        }
                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(final Throwable throwable) {
                        Log.e(TAG, "An error subscribing to WS", throwable);
                    }
                });

        stompClient.connect();
    }
    
    private void disconnect() {
        Log.i(TAG, "WS connection disconnected");
        if (null != stompClient) {
            stompClient.disconnect();
            stompClient = null;
        }
    }
}
```

**Comment by steviemo** [comment]
This could actually be fixed with https://github.com/NaikSoftware/StompProtocolAndroid/commit/0a179d9302a20706b4cc06358ee11313d07f4119 for 1.4.1 release - upgrading codebase for rxjava2 and testing

**Comment by steviemo** [comment]
Same issue with 1.4.1:

```
08-22 10:04:24.607 17214-17598/co.oroson.android D/WebSocketsConnectionProvider: onWebsocketHandshakeReceivedAsClient with response: 101 
08-22 10:04:24.608 17214-17598/co.oroson.android D/WebSocketsConnectionProvider: onOpen with handshakeData: 101 
08-22 10:04:24.608 17214-17598/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: OPENED
08-22 10:04:24.611 17214-17598/co.oroson.android E/WebSocketsConnectionProvider: onError
                                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:153)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onOpen(WebSocketsConnectionProvider.java:98)
                                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketOpen(WebSocketClient.java:311)
                                                                                     at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:720)
                                                                                     at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:301)
                                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:173)
                                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
                                                                                     at java.lang.Thread.run(Thread.java:761)
08-22 10:04:24.611 17214-17598/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: ERROR
08-22 10:04:24.612 17214-17598/co.oroson.android E/WebSocketsConnectionProvider: onError
                                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:153)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
                                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:117)
                                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:339)
                                                                                     at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:722)
                                                                                     at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:301)
                                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:173)
                                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
                                                                                     at java.lang.Thread.run(Thread.java:761)
08-22 10:04:24.612 17214-17598/co.oroson.android D/WebSocketsConnectionProvider: Emit lifecycle event: ERROR
08-22 10:04:24.613 17214-17598/co.oroson.android E/AndroidRuntime: FATAL EXCEPTION: Thread-17
                                                                   Process: co.oroson.android, PID: 17214
                                                                   java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:153)
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
                                                                       at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:117)
                                                                       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:236)
                                                                       at java.lang.Thread.run(Thread.java:761)
```

**Comment by steviemo** [comment]
We also get this exception the odd time on rotate which seems to be related:

```
08-22 11:03:25.426 4206-4443/co.oroson.android W/System.err:     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitMessage(WebSocketsConnectionProvider.java:161)
08-22 11:03:25.426 4206-4443/co.oroson.android W/System.err:     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$300(WebSocketsConnectionProvider.java:30)
08-22 11:03:25.427 4206-4443/co.oroson.android W/System.err:     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:104)
08-22 11:03:25.433 4206-4443/co.oroson.android E/AndroidRuntime: FATAL EXCEPTION: Thread-14
                                                                 Process: co.oroson.android, PID: 4206
                                                                 io.reactivex.exceptions.OnErrorNotImplementedException
                                                                     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                     at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:76)
                                                                     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:66)
                                                                     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
                                                                     at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
                                                                     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:542)
                                                                     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:466)
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitMessage(WebSocketsConnectionProvider.java:161)
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$300(WebSocketsConnectionProvider.java:30)
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:104)
                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:292)
                                                                     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:417)
                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:170)
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
                                                                     at java.lang.Thread.run(Thread.java:761)
                                                                  Caused by: java.util.ConcurrentModificationException
                                                                     at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                                                                     at java.util.HashMap$KeyIterator.next(HashMap.java:885)
                                                                     at ua.naiksoftware.stomp.client.StompClient.callSubscribers(StompClient.java:142)
                                                                     at ua.naiksoftware.stomp.client.StompClient.lambda$connect$1(StompClient.java:111)
                                                                     at ua.naiksoftware.stomp.client.StompClient$$Lambda$3.accept(Unknown Source)
                                                                     at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:62)
                                                                     at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69) 
                                                                     at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79) 
                                                                     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:542) 
                                                                     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:466) 
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitMessage(WebSocketsConnectionProvider.java:161) 
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$300(WebSocketsConnectionProvider.java:30) 
                                                                     at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onMessage(WebSocketsConnectionProvider.java:104) 
                                                                     at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:292) 
                                                                     at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:417) 
                                                                     at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:170) 
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229) 
                                                                     at java.lang.Thread.run(Thread.java:761) 
```

**Comment by steviemo** [comment]
Hey guys - any thoughts on this? I can try a few things out to help debug if you think there is a code smell?

**Comment by forresthopkinsa** [comment]
Can you give this a shot -- I have a fork that does the Rx logic differently -- try using this dependency instead of Master, just because I'm curious if the problem is with the Subscriber lists.

`compile 'com.github.forresthopkinsa:StompProtocolAndroid:1.3.2-RC1'`

**Comment by steviemo** [comment]
I'll give this a go and get back to you

**Comment by steviemo** [comment]
When I revert my project back to rx1 and bring in this library I'm seeing:

Error:(82, 13) Failed to resolve: org.java-websocket:java-websocket:1.3.2

I think your dependency should be org.java-websocket:Java-WebSocket:1.3.2?

**Comment by steviemo** [comment]
Was able to get around this issue by removing:

```
.subscribeOn(Schedulers.io())
.observeOn(AndroidSchedulers.mainThread())
```

from our lifecycle flowable which matches that of StompClient.connect lifecycle flowable (maybe the example app needs tweaked?) and PR https://github.com/NaikSoftware/StompProtocolAndroid/pull/66
