### ISSUE TITLE
Crash on Uknown Mesage type

### ISSUE THREAD

**Issue by adauvalter** [NaikSoftware/StompProtocolAndroid#62]
I try to use this Library with on the Websocket wich works over SocketJs. That means, that also another message can come. For example right know after onConnect
```Send STOMP message: CONNECT
                             version:1.1,1.0
                             accept-version:1.1
                             heart-beat:0,10000
                                                            
                             ��```
I receive a kind of Heartbit message:
```WebSocketsConnectionProvider: Emit STOMP message: o```
At this place the library crash with
```io.reactivex.exceptions.OnErrorNotImplementedException
                                                                                   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                   at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                   at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:76)
                                                                                   at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onError(BasicFuseableSubscriber.java:101)
                                                                                   at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:66)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:542)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:466)
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider.emitMessage(OkHttpConnectionProvider.java:167)
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider.access$200(OkHttpConnectionProvider.java:23)
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider$1.onMessage(OkHttpConnectionProvider.java:91)
                                                                                   at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
                                                                                   at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
                                                                                   at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
                                                                                   at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
                                                                                   at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)
                                                                                Caused by: java.util.NoSuchElementException
                                                                                   at java.util.Scanner.skip(Scanner.java:1747)
                                                                                   at java.util.Scanner.skip(Scanner.java:1764)
                                                                                   at ua.naiksoftware.stomp.client.StompMessage.from(StompMessage.java:80)
                                                                                   at ua.naiksoftware.stomp.client.StompClient$$Lambda$2.apply(Unknown Source)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
                                                                                   at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79) 
                                                                                   at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:542) 
                                                                                   at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onNext(FlowableCreate.java:466) 
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider.emitMessage(OkHttpConnectionProvider.java:167) 
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider.access$200(OkHttpConnectionProvider.java:23) 
                                                                                   at ua.naiksoftware.stomp.OkHttpConnectionProvider$1.onMessage(OkHttpConnectionProvider.java:91) 
                                                                                   at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307) 
                                                                                   at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) 
                                                                                   at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) 
                                                                                   at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) 
                                                                                   at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) 
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) 
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                   at java.lang.Thread.run(Thread.java:761) ```
Because the message doesn't have an empty spaces. But i think, it"ll be ok, to avoid a crash and this place and return a UNKNOWN message type. What do you think about it? It"ll be ok for you, I can create a PR for it.

**Comment by NaikSoftware** [comment]
Yes, is good idea
