### ISSUE TITLE
Fatal exception thrown with okHttp dispatcher

### ISSUE THREAD

**Issue by bataragaradu** [NaikSoftware/StompProtocolAndroid#64]
/com.example.wicked.myapplication E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                                  Process: com.example.wicked.myapplication, PID: 13363
                                                                                  java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
                                                                                      at ua.naiksoftware.stomp.OkHttpConnectionProvider.emitLifecycleEvent(OkHttpConnectionProvider.java:159)
                                                                                      at ua.naiksoftware.stomp.OkHttpConnectionProvider.access$100(OkHttpConnectionProvider.java:23)
                                                                                      at ua.naiksoftware.stomp.OkHttpConnectionProvider$1.onFailure(OkHttpConnectionProvider.java:107)
                                                                                      at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
                                                                                      at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:203)
                                                                                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at java.lang.Thread.run(Thread.java:776)

**Comment by forresthopkinsa** [comment]
What did you do that caused this? How is your connection set up? What's your environment? Give us more information.
