### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Rotenkampf** [NaikSoftware/StompProtocolAndroid#72]
Hello. I faced this exception.
`java.util.ConcurrentModificationException
                                                                            at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
                                                                            at java.util.HashMap$KeyIterator.next(HashMap.java:814)
                                                                            at ua.naiksoftware.stomp.client.StompClient.lambda$topic$3(StompClient.java:167)
                                                                            at ua.naiksoftware.stomp.client.StompClient$$Lambda$5.call(Unknown Source)
                                                                            at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:71)
                                                                            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                            at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                            at rx.Subscriber.unsubscribe(Subscriber.java:98)
                                                                            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:136)
                                                                            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:125)
                                                                            at rx.Subscriber.unsubscribe(Subscriber.java:98)`
In my opinion, this exception appears when more than one subscribers listen the same endpoint.

**Comment by forresthopkinsa** [comment]
What version are you using? 1.4.2?

**Comment by NaikSoftware** [comment]
Fixed in 1.4.4
